name: VPS Session

on:
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 часов максимально
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        # Это создаст SSH сессию, доступную только тебе
